# Generated by Django 3.2.3 on 2021-05-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='updated_at',
        ),
    ]
